apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydepsimple
  name: mydepsimple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydepsimple
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydepsimple
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
