apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydep2
  name: mydep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydep2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
