apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    tier: backend
    app: myapp    
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    # Getting the latest nginx 
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    env:
    - name: "myvar"
      value: abcd
    - name: myvar4
      value: ddddd
    imagePullPolicy: IfNotPresent

